In [1]:
import pandas as pd

from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("spotify_clean.csv")

In [3]:
df.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre'],
      dtype='object')

In [4]:
features = [
    'danceability',
    'energy',
    'loudness',
    'speechiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'valence',
    'tempo'
]

In [5]:
X = df[features]

In [6]:
X.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,0.676,0.4610,-6.746,0.1430,0.0322,0.000001,0.3580,0.715,87.917
1,0.420,0.1660,-17.235,0.0763,0.9240,0.000006,0.1010,0.267,77.489
2,0.438,0.3590,-9.734,0.0557,0.2100,0.000000,0.1170,0.120,76.332
3,0.266,0.0596,-18.515,0.0363,0.9050,0.000071,0.1320,0.143,181.740
4,0.618,0.4430,-9.681,0.0526,0.4690,0.000000,0.0829,0.167,119.949

In [7]:
X.shape

(113549, 9)

In [8]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [9]:
X_scaled

array([[ 0.62839367, -0.72132759,  0.29880036, ...,  0.7580939 ,
         0.92898358, -1.14299362],
       [-0.84789057, -1.89638213, -1.79422774, ..., -0.59126379,
        -0.79939532, -1.4909088 ],
       [-0.74408933, -1.12761763, -0.29744027, ..., -0.50725709,
        -1.36651965, -1.52951044],
       ...,
       [ 0.35735711, -1.2471147 , -0.52911208, ..., -0.68104596,
         1.03700726,  0.34038354],
       [ 0.11515423, -0.54208198, -0.52791481, ...,  0.29605702,
        -0.23612898,  0.4598918 ],
       [-0.23661663, -0.61776346, -0.39122644, ..., -0.65269369,
         0.90197766, -1.43389048]], shape=(113549, 9))

In [10]:
scaled_df = pd.DataFrame(
    X_scaled,
    columns=features
)

In [11]:
scaled_df.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,0.628394,-0.721328,0.298800,0.551483,-0.849230,-0.503538,0.758094,0.928984,-1.142994
1,-0.847891,-1.896382,-1.794228,-0.079182,1.837684,-0.503524,-0.591264,-0.799395,-1.490909
2,-0.744089,-1.127618,-0.297440,-0.273960,-0.313535,-0.503542,-0.507257,-1.366520,-1.529510
3,-1.735968,-2.320198,-2.049645,-0.457392,1.780439,-0.503313,-0.428501,-1.277786,1.987275
4,0.293923,-0.793026,-0.286864,-0.303272,0.466809,-0.503542,-0.686296,-1.185194,-0.074292

In [12]:
scaled_df.mean()

danceability        2.422938e-16
energy              3.604370e-17
loudness            9.611653e-17
speechiness        -1.041262e-16
acousticness       -1.601942e-17
instrumentalness    3.203884e-17
liveness            4.805827e-17
valence             3.203884e-17
tempo              -1.501821e-16
dtype: float64

In [13]:
scaled_df.std()

danceability        1.000004
energy              1.000004
loudness            1.000004
speechiness         1.000004
acousticness        1.000004
instrumentalness    1.000004
liveness            1.000004
valence             1.000004
tempo               1.000004
dtype: float64

In [14]:
scaled_df.to_csv("spotify_scaled.csv", index=False)